export const APP_SET_WINDOW_DEFAULTS = 'AppSetWindowDefaults'
export const APP_NAV_MENU_ACTION = 'AppNavMenuAction'
export const APP_APP_ACTIONS = 'AppAppActions'
export const APP_GET_PIC_LIST_DONE = 'AppGetPicListDone'
export const APP_SET_CURRENT_COLUMN = 'AppSetCurrentColumn'

export const PICS_SELECT_GENUS = 'PicsSelectGenus'
export const PICS_SELECT_SPECIES = 'PicsSelectSpecies'
export const PICS_SELECT_PART = 'PicsSelectPart'
export const PICS_MOVE_LEFT = 'PicsMoveLeft'
export const PICS_MOVE_RIGHT = 'PicsMoveRight'
export const PICS_MOVE_UP = 'PicsMoveUp'
export const PICS_MOVE_DOWN = 'PicsMoveDown'
export const PICS_SELECT_JUMP_NODE = 'PicsSelectJumpNode'
export const PICS_GET_IMAGE_LIST_DONE = 'PicsGetImageListDone'
export const PICS_APPLY_FILTER = 'PicsApplyFilter'

export const INFO_SELECT_GENUS = 'InfoSelectGenus'
export const INFO_SELECT_SPECIES = 'InfoSelectSpecies'
export const INFO_GET_SPECIES_LIST_DONE = 'InfoGetSpeciesListDone'
export const INFO_GET_FILTER_LIST_DONE = 'InfoGetFilterListDone'
export const INFO_GET_GENUS_LIST_DONE = 'InfoGetGenusListDone'
export const INFO_CLEAR_FILTER = 'InfoClearFilter'
export const INFO_CHANGE_FILTER_VALUE = 'InfoChangeFilterValue'
